---
- hosts: all
  remote_user: kato
  become: yes  # Add this line to run tasks with elevated privileges
  tasks:
    - name: Install required packages
      apt:
        name:
          - htop
          - byobu
          - net-tools
          - ebtables
          - ipset
          - open-iscsi
          - conntrack
          - socat
        state: present

