---
- hosts: all
  remote_user: kato
  become: yes
  gather_facts: no
  tasks:
    - name: Install required packages
      apt:
        name:
          - htop
          - byobu
          - net-tools
          - ebtables
          - ipset
          - open-iscsi
          - conntrack
          - socat
          - curl
        state: present