---
- hosts: all
  remote_user: kato
  become: yes
  gather_facts: no
  tasks:
    - name: Disable swap
      shell: |
        swapoff -a
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
      changed_when: false