- hosts: all
  become: yes
  become_user: root
  remote_user: root
  become_method: sudo
  gather_facts: no
  vars:
    ansible_become_pass: " "
  tasks:
  - name: "Disable swap"
    shell: |
              swapoff -a
              sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
