---
- hosts: master
  remote_user: kato
  become: yes
  gather_facts: no
  tasks:
    - name: Download KubeKey v3.1.9
      shell: |
        if [ ! -f /home/kato/kk ]; then
          cd /home/kato
          curl -sfL https://get-kk.kubesphere.io | VERSION=v3.1.9 sh -
          chmod +x kk
        fi
      args:
        creates: /home/kato/kk
      become_user: kato
      retries: 3
      delay: 10
    
    - name: Create KubeKey config with Kubernetes v1.33.1
      shell: |
        if [ ! -f /home/kato/config-sample.yaml ]; then
          cd /home/kato
          ./kk create config --with-kubernetes v1.33.1
        fi
      args:
        creates: /home/kato/config-sample.yaml
      become_user: kato
      environment:
        PATH: "/home/kato:{{ ansible_env.PATH }}"
      retries: 3
      delay: 10