- hosts: master
  become: yes
  remote_user: kato
  gather_facts: no
  tasks: 
    - name: "Download kubekey"
      shell: |
              curl -sfL https://get-kk.kubesphere.io | VERSION=v3.0.2 sh -
              chmod +x kk
              ./kk create config --with-kubernetes v1.23.10
