---
- hosts: master
  remote_user: kato
  become: yes
  gather_facts: no
  tasks:
    - name: Copying configuration file to server
      become: true
      copy:
        src: /Users/bruno/infra/vm-boxs/config-sample.yaml
        dest: ~/
        owner: kato
        group: sudo
    - name: "Install k8 cluster"
      shell: |
              ./kk create cluster -f ~/config-sample.yaml -y
